apiVersion: v1

kind: Service

metadata:
  name: udagram-user-service
  labels: 
    run: udagram-user-service

spec:
  ports:
  - port: 4000
    protocol: TCP
  selector:
    run: udagram-user-service