language: node_js
node_js:
    - 14

services:
    - docker

# Pre-testing installs
install:
    - echo "Nothing to install"

# Scripts to be run, such as tests
before_script:
    - echo "No tests available"

script:
    # Print the version for logging.
    - docker --version 

    # Build docker image
    - docker build -t udagram-feed-service .

    # Tag docker image
    - docker tag udagram-feed-service phoenix254/udagram-feed-service:v1

after_success:
    # Deploy
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push phoenix254/udagram-feed-service