apiVersion: v1

kind: Service

metadata:
  name: udagram-feed-service
  labels: 
    run: udagram-feed-service

spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: udagram-feed-service