apiVersion: v1

kind: Service

metadata:
  name: udagram-feed-service
  labels: 
    run: udagram-feed-service

spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: udagram-feed-service