apiVersion: apps/v1

kind: Deployment

metadata:
  name: udagram-reverse-proxy
  labels:
    service: udagram-reverse-proxy

spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-reverse-proxy
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
    spec:
      containers:
      - name: udagram-reverse-proxy
        image: phoenix254/udagram-reverse-proxy
        ports:
        - containerPort: 8080
      restartPolicy: Always