apiVersion: v1

kind: Service

metadata:
  name: udagram-reverse-proxy
  labels: 
    run: udagram-reverse-proxy

spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverse-proxy